export const TRACK_LIST_REQUEST = 'TRACK_LIST_REQUEST'
export const TRACK_LIST_SUCCESS = 'TRACK_LIST_SUCCESS'
export const TRACK_LIST_FAIL = 'TRACK_LIST_FAIL'

export const TRACK_CREATE_REQUEST = 'TRACK_CREATE_REQUEST'
export const TRACK_CREATE_SUCCESS = 'TRACK_CREATE_SUCCESS'
export const TRACK_CREATE_FAIL = 'TRACK_CREATE_FAIL'

export const TRACK_DELETE_REQUEST = 'TRACK_DELETE_REQUEST'
export const TRACK_DELETE_SUCCESS = 'TRACK_DELETE_SUCCESS'
export const TRACK_DELETE_FAIL = 'TRACK_DELETE_FAIL'

export const TRACK_DETAILS_REQUEST = 'TRACK_DETAILS_REQUEST'
export const TRACK_DETAILS_SUCCESS = 'TRACK_DETAILS_SUCCESS'
export const TRACK_DETAILS_FAIL = 'TRACK_DETAILS_FAIL'
export const TRACK_DETAILS_RESET = 'TRACK_DETAILS_RESET'

export const TRACK_NUMBER_DETAILS_REQUEST = 'TRACK_NUMBER_DETAILS_REQUEST'
export const TRACK_NUMBER_DETAILS_SUCCESS = 'TRACK_NUMBER_DETAILS_SUCCESS'
export const TRACK_NUMBER_DETAILS_FAIL = 'TRACK_NUMBER_DETAILS_FAIL'

export const TRACK_UPDATE_REQUEST = 'TRACK_UPDATE_REQUEST'
export const TRACK_UPDATE_SUCCESS = 'TRACK_UPDATE_SUCCESS'
export const TRACK_UPDATE_FAIL = 'TRACK_UPDATE_FAIL'
export const TRACK_UPDATE_RESET = 'TRACK_UPDATE_RESET'

export const SHIPMENT_HISTORY_REQUEST = 'SHIPMENT_HISTORY_REQUEST'
export const SHIPMENT_HISTORY_SUCCESS = 'SHIPMENT_HISTORY_SUCCESS'
export const SHIPMENT_HISTORY_FAIL = 'SHIPMENT_HISTORY_FAIL'